services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    networks:
      - internal

  backend:
    build:
      context: ./backend
    restart: unless-stopped
    env_file:
      - ./backend/.env.production
    ports:
      - '127.0.0.1:3002:4001'
    networks:
      - internal
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: /api
    restart: unless-stopped
    ports:
      - '127.0.0.1:5555:80'
    networks:
      - internal

networks:
  internal:

volumes:
  mongo-data:
